version: "3"

services:
  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # コードの変更を仮想環境でもリアルタイムで変更したい
    volumes:
      - .:/app
    depends_on:
      - nginx
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    # コードの変更を仮想環境でもリアルタイムで変更したい
    volumes:
      - ./backend:/app
